---
dependencies: []

galaxy_info:
  author: Adham Helal
  description: "Deploy sonar qube on Ubuntu 12.04"
  min_ansible_version: 1.6
  platforms:
  - name: Ubuntu
    versions:
    - precise
  categories:
  - development
